### ISSUE TITLE
Automatic serverlist announce

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#11]
I think it would be useful if multiserver would take care of the announce to the serverlist, because:
* It could display how many players are online on all servers (excluding rpc ofc) and suppress sending rpc to the serverlist
* It would remove pain with having to use `bind_address` in the configuration file
* The version sent to the serverlist could include that multiserver is used

**Comment by HimbeerserverDE** [comment]
Implemented
