### ISSUE TITLE
CAO mapping 

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#13]
(Will partiall fix #8)

There is already a cao_mapping branch, just opening this issue for discussion

**Comment by EliasFleckenstein03** [comment]
ToDo: Send the messages of the new player CAO when redirecting to another server from the AO add remove command in an AO messages rather than an AO add/rm command - when an AO is added that already exists the command will be ignored, meaning that the messages are not parsed as well, which results in breakage when it comes to animations e.g.

**Comment by HimbeerserverDE** [comment]
This is merged, there are some problems with animations though.

**Comment by HimbeerserverDE** [comment]
It might have something to do with the m_id variable that is read from the initialization data. It seems to be an attribute of the ActiveObject class and I think it's just the object ID. Replacing it just like the regular ID should do the trick.

**Comment by EliasFleckenstein03** [comment]
Commands that dont have CAO mapping implemented yet:
- [ ] AO messages -> attach
- [ ] Play Sound
- [ ] Add particlespawner

**Comment by EliasFleckenstein03** [comment]
This seems do be done. Can it be closed?
