### ISSUE TITLE
If one of the servers is running creative, clients connected to any server will think they have creative tool capabilities - only client side tho.

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#16]

**Comment by HimbeerserverDE** [comment]
Apparently there is a hand list (but you have to set the size before you can use it). I don't know exactly if and how it works though. My idea: Hands get item names (format: "multiserver:hand_SERVERNAME") instead of only sending the best one. On join or redirect the only itemstack in the hand list is updated accordingly.

**Comment by EliasFleckenstein03** [comment]
The problem is that the hand list toolcaps are only used for nodes that would not be diggable at all otherwise. Most games do the hand capabilities by overriding the ':' item - this results in the item in hand list not being recognized except for nodes that are not diggable with the used tool. 
```c++
// NOTE: Similar piece of code exists on the server side for
// cheat detection.
// Get digging parameters
DigParams params = getDigParams(nodedef_manager->get(n).groups,
		&selected_item.getToolCapabilities(itemdef_manager));

// If can't dig, try hand
if (!params.diggable) {
	params = getDigParams(nodedef_manager->get(n).groups,
			&hand_item.getToolCapabilities(itemdef_manager));
}
```

The solution would be: 
- not sending the toolcaps of the : item to the player
- when connecting to the network or redirecting to a server, the size of the hand list is set to 1 and a : item with tool capabilities in the metadata is moved into the hand list, the toolcaps need to be the tool capabilities that the : item definition contains on this server.
- everytime the server moves a item into the hand list, its toolcaps are set in the metadata to the tool caps of : item definition of that server

The only problem: If the server moves an item that has toolcaps in the definition or metadata to the handlist, that is ignored by the client. A solution to this would be combining the toolcaps (the values from the : definition need to be used first, even if they are slower than the ones from the toolcaps of the item moved by the server into the hand list) and using that as the toolcaps metadata sent to the client.

**Comment by HimbeerserverDE** [comment]
To solve the only problem I would only replace the toolcaps if the item name is empty/:
This would allow SSMs to override the hand capabilities (if they're putting an item that is not : into the hand list).

**Comment by HimbeerserverDE** [comment]
I added all the logic (slightly modified but the original one didn't work either) but for some reason I can't dig anything with the hand (exceptions: devtest chest of everything, devtest light source, mineclone2 sugar canes) and I have no idea why.

**Comment by HimbeerserverDE** [comment]
I found out why: The hand list gets overwritten or deleted by the minetest server because step 3 isn't implemented. Also my approach isn't as good as yours. I'm going to completely reimplement this when I have time.

**Comment by EliasFleckenstein03** [comment]
Well, if step 3 wasn't implemented I fully understand why it does not work xD

**Comment by HimbeerserverDE** [comment]
I have made some progress with implementing step 2 but there are still some bugs I should fix before committing it.

**Comment by HimbeerserverDE** [comment]
Everything done except for solving "the only problem"

**Comment by EliasFleckenstein03** [comment]
I actually don't know of a game implementing "the only problem".
