### ISSUE TITLE
Uses rudp.ErrClosed, which is deprecated.

### ISSUE THREAD

**Issue by anon55555** [HimbeerserverDE/multiserver#18]
You should use net.ErrClosed (added in Go 1.16) instead.

**Comment by EliasFleckenstein03** [comment]
I don't think it's a good idea to change the required version of go

**Comment by anon55555** [comment]
Why not?

**Comment by EliasFleckenstein03** [comment]
Because this already happened to my server using multiserver. Luckily its not in production yet.
```
../go/src/github.com/anon55555/mt/rudp/listen.go:65:17: undefined: net.ErrClosed
../go/src/github.com/anon55555/mt/rudp/net.go:9:17: undefined: net.ErrClosed
../go/src/github.com/anon55555/mt/rudp/net.go:29:22: undefined: net.ErrClosed
../go/src/github.com/anon55555/mt/rudp/peer.go:95:19: undefined: net.ErrClosed
../go/src/github.com/anon55555/mt/rudp/peer.go:111:10: undefined: net.ErrClosed
../go/src/github.com/anon55555/mt/rudp/send.go:129:15: undefined: net.ErrClosed
```

**Comment by anon55555** [comment]
You should update Go then.

**Comment by EliasFleckenstein03** [comment]
It needs to be automized. Will `sudo snap refresh go --edge` do it?

**Comment by anon55555** [comment]
Maybe I'll give some advance warning if I do something like this in future.

**Comment by anon55555** [comment]
> It needs to be automized. Will `sudo snap refresh go --edge` do it?

Edge will give you the current development version, 1.16/stable is the latest release but it seems latest/stable is still on 1.15.8.

**Comment by anon55555** [comment]
or you could do this: ```sh
cd /usr/local
rm -rf go
curl https://golang.org/dl/go1.16.linux-amd64.tar.gz | tar xz
``` then put /usr/local/go/bin in your PATH

**Comment by anon55555** [comment]
`sudo snap refresh go --channel 1.16/stable` should work too

**Comment by EliasFleckenstein03** [comment]
Ok, thanks a lot.

**Comment by HimbeerserverDE** [comment]
Replaced rudp.ErrClosed with net.ErrClosed and updated go.mod, can this be closed now?

**Comment by anon55555** [comment]
yes
