### ISSUE TITLE
Idea: Log out rpc when there is another player online and do the modchannel communication over that player

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#25]

**Comment by HimbeerserverDE** [comment]
This could be done by disconnecting, then replacing the peer with the server peer the client is connected to, setting its useRpc field to true and joining the modchannel (if it hasn't already been done). When the player leaves or switches to a different server the proxy searches for a different client that is still connected to this server. If one is found the above process is repeated using that player's connection. If not, the RPC user is logged in again. The reconnect functionality will only attempt to reconnect if no players are connected to a server.
