### ISSUE TITLE
Yet another crash

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#35]
2021/02/28 14:26:22 error processing raw pkt: 0003: ctl: disco: can't close: use of closed network connection
panic: runtime error: slice bounds out of range [:2] with capacity 0

goroutine 135491 [running]:
main.init.7.func1.1.1(0xc000aaa140)
        /home/elidragonmt/multiserver/rpc.go:305 +0x3e7
created by main.init.7.func1.1
        /home/elidragonmt/multiserver/rpc.go:291 +0xdd

**Comment by HimbeerserverDE** [comment]
Fixed: https://github.com/HimbeerserverDE/multiserver/commit/9c5f827fc84734f2e288821b5532865aca0904c9
