### ISSUE TITLE
Remove rpc nametag and collisionbox setting from multiserver_api mod to proxy

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver#38]
I figured out how to hide the nametag + collisionbox in MineClone, you need to run it in a globalstep and depend on mcl_playerplus. But the multiserver API should be portable between games - The solution is to just don't send the activeobject for the rpc player to any clients.

**Comment by HimbeerserverDE** [comment]
Is it possible to use an optional dependency?

**Comment by HimbeerserverDE** [comment]
#25 will fix this
