### ISSUE TITLE
[Feature] Support postgresql for auth database

### ISSUE THREAD

**Issue by grapereader** [HimbeerserverDE/multiserver#79]
- Support using postgresql for auth database, for backwards compatibility with existing databases
- Use the same DB schema as minetest 

Issues (from what I have observed by _replacing_ sqlite with postgresql):
1. Schema is not the same as sqlite (user_privileges instead of privileges, user_privileges -> auth by id instead of by name, etc)
2. SQL parameter syntax is slightly different ($x instead of ?) so it's not possible to share statements between sqlite and postgresql even if the schemas were made consistent.

This could be addressed by a "database provider" abstraction similar to Minetest's. Already auth.go, ban.go and privilege.go expose a de-facto interface. If this was extracted into a golang interface, it could be implemented by a postgresql provider.

So the first step should be to replace static functions with a golang interface for the _current_ sqlite database, so it can be swapped out. Then a postgresql provider can be added after.

**Comment by anon55555** [comment]
I don't see much point in adding postgresql support because people can just convert their auth db to sqlite using the --migrate-auth minetest option.

**Comment by grapereader** [comment]
> 
> 
> I don't see much point in adding postgresql support because people can just convert their auth db to sqlite using the --migrate-auth minetest option.

What if you want to have an unproxied server share the same users + passwords? Just one example.

**Comment by anon55555** [comment]
I don't think you can do that even when mt uses sqlite, the README says "Note: This shouldn't be used with existing minetest servers without moving authentication data (not the database files) to the proxy and then deleting the auth databases on the minetest servers! Not doing so can cause proxy <-> mt_server authentication to fail."

**Comment by grapereader** [comment]
> 
> 
> I don't think you can do that even when mt uses sqlite, the README says "Note: This shouldn't be used with existing minetest servers without moving authentication data (not the database files) to the proxy and then deleting the auth databases on the minetest servers! Not doing so can cause proxy <-> mt_server authentication to fail."

Yes, you would delete the auth databases used by the _proxied_ servers and let them use sqlite. Then, point multiserver at the postgres database. The postgres database can still be shared with _unproxied_ servers.

Again, just a contrived example. What if you had a web interface, or a forum? This would also need to share the auth database.

**Comment by grapereader** [comment]
> 
> 
> I don't think you can do that even when mt uses sqlite, the README says "Note: This shouldn't be used with existing minetest servers without moving authentication data (not the database files) to the proxy and then deleting the auth databases on the minetest servers! Not doing so can cause proxy <-> mt_server authentication to fail."

All I'm trying to say is that postgres can be more robust in production, so lots of admins may want to keep their existing databases.

The servers managed by multiserver would, as you say, have their own internal sqlite databases reset to avoid the proxy <-> mt_server authentication failures mentioned in the readme.

**Comment by HimbeerserverDE** [comment]
PostgreSQL is now supported but the scheme isn't the same.

**Comment by grapereader** [comment]
Awesome.

I have some draft changes https://github.com/grapereader/multiserver/commit/a47022a1116592ba6709e9458f9a73484998e32b to make the schemas consistent, without modifying existing sqlite databases.

After I do some testing to make sure it all works I wonder what the odds are of getting this merged in a PR?

**Comment by HimbeerserverDE** [comment]
Using the MT schema doesn't make much sense to me because I've added PostgreSQL support to my DB converter, but I would very likely merge the other changes after testing them.

**Comment by grapereader** [comment]
Personally, I also have a forum sharing this database. So there's my investment in it 😛 

I suppose I _could_ change my forum to use multiserver's schema... and put a multiserver instance in front of every server 🤷‍♂️ 

Guess it would "just be nice" if everything worked seamlessly together.

**Comment by grapereader** [comment]
Yeah OK. I can cope. As long as multiserver supports postgres in some fashion 👍

**Comment by HimbeerserverDE** [comment]
I'm deprecating this project in favor of [mt-multiserver-proxy](https://github.com/HimbeerserverDE/mt-multiserver-proxy). It can be used with its own file based authentication system or use Minetest sqlite3 or postgres databases directly at the cost of not being able to remember the last server a user played on. It is also possible to convert between different backends using its [mt-auth-convert tool](https://github.com/HimbeerserverDE/mt-multiserver-proxy/blob/main/doc/auth_backends.md#mt-auth-convert).

The sqlite3 and postgres schemas are consistent with the ones Minetest uses.

If you have any questions or requests please open an issue on the new repo.
