### ISSUE TITLE
Minetest client outdated message when using i3

### ISSUE THREAD

**Issue by grapereader** [HimbeerserverDE/multiserver#84]
Whatever new network features [i3](https://github.com/minetest-mods/i3) is making use of, multiserver (likely MT/rudp) does not support them.

Using Minetest 5.5.0, latest multiserver, the inventory does not load (default inventory appears instead) and this message appears on login:

![image](https://user-images.githubusercontent.com/1329614/116790391-b41c3400-aa68-11eb-9bac-fee336c6fadb.png)

**Comment by HimbeerserverDE** [comment]
This happens because the formspec version isn't sent in the TOSERVER_CLIENT_READY packet. I'm going to fix this soon.
